import { singleton } from "tsyringe";

const stopWordsMap = {
  aca: null,
  ahi: null,
  ajena: null,
  ajenas: null,
  ajeno: null,
  ajenos: null,
  al: null,
  algo: null,
  algun: null,
  alguna: null,
  alguno: null,
  alla: null,
  alli: null,
  ambos: null,
  ante: null,
  antes: null,
  aquel: null,
  aquella: null,
  aquellas: null,
  aquello: null,
  aquellos: null,
  aqui: null,
  arriba: null,
  asi: null,
  atras: null,
  aun: null,
  aunque: null,
  bajo: null,
  bastante: null,
  bien: null,
  cabe: null,
  cada: null,
  casi: null,
  cierto: null,
  ciertos: null,
  cierta: null,
  ciertas: null,
  como: null,
  con: null,
  conmigo: null,
  conseguimos: null,
  conseguir: null,
  consigo: null,
  consigue: null,
  consiguen: null,
  consigues: null,
  contigo: null,
  contra: null,
  cual: null,
  cuales: null,
  cualquier: null,
  cualquiera: null,
  cualesquiera: null,
  cuan: null,
  cuando: null,
  cuanto: null,
  cuanta: null,
  cuantas: null,
  de: null,
  dejar: null,
  del: null,
  demas: null,
  demasiada: null,
  demasiado: null,
  demasiados: null,
  dentro: null,
  desde: null,
  donde: null,
  el: null,
  ella: null,
  ellas: null,
  ello: null,
  ellos: null,
  empleais: null,
  emplean: null,
  emplear: null,
  empleas: null,
  empleo: null,
  en: null,
  encima: null,
  entonces: null,
  entre: null,
  era: null,
  eras: null,
  eramos: null,
  eran: null,
  eres: null,
  es: null,
  esa: null,
  ese: null,
  eso: null,
  esos: null,
  esta: null,
  estas: null,
  estaba: null,
  estado: null,
  estais: null,
  estamos: null,
  estan: null,
  estar: null,
  este: null,
  esto: null,
  estos: null,
  estoy: null,
  etc: null,
  fin: null,
  fue: null,
  fueron: null,
  fui: null,
  fuimos: null,
  gueno: null,
  ha: null,
  hace: null,
  haces: null,
  haceis: null,
  hacemos: null,
  hacen: null,
  hacer: null,
  hacia: null,
  hago: null,
  hasta: null,
  incluso: null,
  intenta: null,
  intentas: null,
  intentais: null,
  intentamos: null,
  intentan: null,
  intentar: null,
  intento: null,
  ir: null,
  jamas: null,
  junto: null,
  juntos: null,
  la: null,
  las: null,
  lo: null,
  los: null,
  largo: null,
  mas: null,
  me: null,
  menos: null,
  mi: null,
  mis: null,
  mia: null,
  mias: null,
  mientras: null,
  mio: null,
  mios: null,
  misma: null,
  mismas: null,
  mismo: null,
  mismos: null,
  modo: null,
  mucha: null,
  muchas: null,
  muchisima: null,
  muchisimas: null,
  muchisimo: null,
  muchisimos: null,
  mucho: null,
  muchos: null,
  muy: null,
  nada: null,
  ni: null,
  ningun: null,
  ninguna: null,
  ningunas: null,
  ninguno: null,
  ningunos: null,
  no: null,
  nos: null,
  nosotras: null,
  nosotros: null,
  nuestra: null,
  nuestras: null,
  nuestro: null,
  nuestros: null,
  nunca: null,
  os: null,
  otra: null,
  otras: null,
  otro: null,
  otros: null,
  para: null,
  parecer: null,
  pero: null,
  poca: null,
  pocas: null,
  poco: null,
  pocos: null,
  podéis: null,
  podemos: null,
  poder: null,
  podria: null,
  podrias: null,
  podriais: null,
  podriamos: null,
  podrian: null,
  por: null,
  que: null,
  porque: null,
  primero: null,
  puede: null,
  pueden: null,
  puedo: null,
  pues: null,
  querer: null,
  quien: null,
  quienes: null,
  quienesquiera: null,
  quienquiera: null,
  quiza: null,
  quizas: null,
  sabe: null,
  sabes: null,
  saben: null,
  sabeis: null,
  sabemos: null,
  saber: null,
  se: null,
  segun: null,
  ser: null,
  si: null,
  siempre: null,
  siendo: null,
  sin: null,
  sino: null,
  so: null,
  sobre: null,
  sois: null,
  solamente: null,
  solo: null,
  somos: null,
  soy: null,
  sr: null,
  sra: null,
  sres: null,
  sta: null,
  su: null,
  sus: null,
  suya: null,
  suyas: null,
  suyo: null,
  suyos: null,
  tal: null,
  tales: null,
  tambien: null,
  tampoco: null,
  tan: null,
  tanta: null,
  tantas: null,
  tanto: null,
  tantos: null,
  te: null,
  teneis: null,
  tenemos: null,
  tener: null,
  tengo: null,
  ti: null,
  tiempo: null,
  tiene: null,
  tienen: null,
  toda: null,
  todas: null,
  todo: null,
  todos: null,
  tomar: null,
  trabaja: null,
  trabajo: null,
  trabajais: null,
  trabajamos: null,
  trabajan: null,
  trabajar: null,
  trabajas: null,
  tras: null,
  tu: null,
  tus: null,
  tuya: null,
  tuyas: null,
  tuyo: null,
  tuyos: null,
  ultimo: null,
  usa: null,
  usas: null,
  usais: null,
  usamos: null,
  usan: null,
  usar: null,
  uso: null,
  usted: null,
  ustedes: null,
  va: null,
  van: null,
  vais: null,
  valor: null,
  vamos: null,
  varias: null,
  varios: null,
  vaya: null,
  verdadera: null,
  vosotras: null,
  vosotros: null,
  voy: null,
  vuestra: null,
  vuestras: null,
  vuestro: null,
  vuestros: null,
  y: null,
  ya: null,
  yo: null,
  // Cusmom
  id: null,
  cedula: null,
  lumniportal: null,
  lumni: null,
  portal: null,
};

@singleton()
export default class KeywordsServices {

  removeStopWords(words: string[]): string[] {
    return words.filter(w => (stopWordsMap as any)[w] === undefined);
  }

  extractKeyWordsFromString(str: string): string {
    const words = str
      .toString()
      .normalize("NFD")
      .replace(/[\u0300-\u036f]/g, "")
      .toLowerCase()
      .split(/[^A-Za-z0-9]/g)
      .filter(x => x.length > 0);

    const keyWords = this.removeStopWords(words).join(" ");
    return keyWords;
  }

  extractKeyWordsFromOptions(values: string[], options: { value: string; text: string }[]): string {
    return values.map(v => {
      const option = options.find(o => o.value === v);
      if (option === undefined) return null;
      return this.extractKeyWordsFromString(option.text);
    }).filter(x => x !== null).join(" ");
  }

  extractKeyWordsFromArray(strs: (string | null)[]): string {
    return strs.filter(x => x !== null).map(x => this.extractKeyWordsFromString(x!)).filter(x => x !== "").join(" ");
  }

  concatKeyWords(keyWords: string[]) {
    return keyWords.filter(x => x !== "").join(" ");
  }

  keyWordsToArray(keyWords: string): string[] {
    if(keyWords === "") return [];
    return keyWords.split(" ");
  }

}
